name: "Xcode latest"
description: Select available version of Xcode.

runs:
  using: "composite"
  steps:
    - name: Select latest Xcode
      run: |
        echo "🔍 Looking for Xcode latest..."
        # Find the highest version available
        xcode=$(ls /Applications | grep Xcode | sort -Vr | head -n 1)
        echo "Using: $xcode"
        sudo xcode-select -s "/Applications/$xcode/Contents/Developer"
      shell: bash

    - name: Show selected Xcode version
      run: xcodebuild -version
      shell: bash
