name: Zero-Setup SSH into macOS Runner (tmate)

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          # This instructs the action to halt the workflow and wait for your input
          limit-access-to-actor: false
